### ISSUE TITLE
Storybook is broken for some components

### ISSUE THREAD

**Issue by kamthamc** [steven-mercatante/react-timeline#30]
https://react-timeline.com/?path=/story/atoms-imageatom--remote-url
https://react-timeline.com/?path=/story/atoms-imageatom--local-image
https://react-timeline.com/?path=/story/controls-button--button
https://react-timeline.com/?path=/story/controls-button--with-on-click-handler

**Comment by steven-mercatante** [comment]
Thanks for catching this!
